name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update composer
        run: composer update
      - name: Install dependencies
        run: composer install 
      - name: Run Server
        run: php artisan serve
