name: Laravel

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.x"

      - name: Install dependencies
        run: composer install

      - name: Create .env file
        run: cp .env.example .env

      - name: Generate key
        run: php artisan key:generate

      - name: Run PHPUnit tests
        run: php artisan test

  larvel-deploy:
    runs-on: ubuntu-latest
    needs: laravel-tests
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/laravel-project/
            git pull origin main
            git status
            composer update
            composer install
            php artisan migrate
            php artisan serve
